#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2024 ByteDance.

set -e

ret=0

while read -r line; do
  # Skip upstream commits
  if git log "$line" -1 | grep -i -E "commit\s+[0-9a-f]{40}\s+upstream|upstream\s+commit\s+[0-9a-f]{40}|cherry picked from commit [0-9a-f]{40}" >/dev/null; then
    continue
  fi

  if ! ./scripts/checkpatch.pl -g "$line" --no-summary; then
    ret=1
  fi

done < <(eval git log --oneline --no-color --no-merges "$@" --no-abbrev-commit | grep -E -o "[0-9a-f]{40}")

exit $ret
